<?php

return [
    'apartments_db' => [
        ['sommary_title' => 'Appartamento Roma Via Sardegna','description' =>'Bell appartamento luminoso', 'room_number' =>'3','guest_number' =>'2', 'wc_number' =>'1', 'square_meters' =>'90', 'latitude' =>'41.909377', 'longitude' =>'12.491740', 'cover_image' => 'https://media-cdn.tripadvisor.com/media/vr-splice-j/05/d2/7a/e5.jpg'],
        ['sommary_title' => 'Appartamento Roma Via Po','description' =>'Bell appartamento spazioso a due passi dal teatro', 'room_number' =>'5','guest_number' =>'4', 'wc_number' =>'1', 'square_meters' =>'170', 'latitude' =>'41.911637', 'longitude' =>'12.493542', 'cover_image' => 'https://www.glamour.de/var/condenast/storage/images/media/images/artikelbilder/feature-bilder/einzimmerwohnung-quer/15183724-1-ger-DE/einzimmerwohnung-quer_generic_huge.jpg'],
        ['sommary_title' => 'Appartamento Roma Quartiere IV Salario','description' =>'Tranquillo, molti negozi sotto casa', 'room_number' =>'4','guest_number' =>'2', 'wc_number' =>'1', 'square_meters' =>'80', 'latitude' =>'41.917035', 'longitude' =>'12.499258', 'cover_image' => 'https://q-xx.bstatic.com/images/hotel/max1024x768/100/100304015.jpg'],
        ['sommary_title' => 'Appartamento Roma Quartiere III Pinciano','description' =>'Appartamento ristrutturato vicino alla banca', 'room_number' =>'6','guest_number' =>'5', 'wc_number' =>'2', 'square_meters' =>'190', 'latitude' =>'41.922679', 'longitude' =>'12.484712', 'cover_image' => 'https://r-cf.bstatic.com/images/hotel/max1024x768/241/241940060.jpg'],
        ['sommary_title' => 'Appartamento Milano Porta Garibaldi','description' =>'Appartamento ristrutturato, fermata autobus, wifi', 'room_number' =>'5','guest_number' =>'3', 'wc_number' =>'1', 'square_meters' =>'100', 'latitude' =>'45.480205', 'longitude' =>'9.190106', 'cover_image' => 'https://previews.123rf.com/images/bialasiewicz/bialasiewicz1709/bialasiewicz170900528/85534781-braided-blanket-on-beige-sofa-with-patterned-black-and-white-pillows-in-scandinavian-style.jpg'],
        ['sommary_title' => 'Appartamento Milano Tre Torri','description' =>'200 metri dalla metro, bell appartamento new style', 'room_number' =>'4','guest_number' =>'2', 'wc_number' =>'1', 'square_meters' =>'120', 'latitude' =>'45.470589', 'longitude' =>'9.156761', 'cover_image' => 'https://lefkada-villas.s3.amazonaws.com/lefkada-rentals/uploads/production/image/image/16796/normal_3ab3da88e45c5677e7bbb3f352b83533.jpg'],
        ['sommary_title' => 'Appartamento Milano Simonetta','description' =>'Super occasione,libero dal 1 maggio trilocale con parcheggio auto', 'room_number' =>'3','guest_number' =>'2', 'wc_number' =>'1', 'square_meters' =>'110', 'latitude' =>'45.489516', 'longitude' =>'9.167443', 'cover_image' => 'https://d1bvpoagx8hqbg.cloudfront.net/originals/modern-apartment-w-free-internet-1min-train-station-15min-university-fbba06df7372c0f5189f5724e652040e.jpg'],
        ['sommary_title' => 'Appartamento Parigi Plaine de Monceaux','description' =>'Appartamento ampio e luminoso', 'room_number' =>'9','guest_number' =>'7', 'wc_number' =>'3', 'square_meters' =>'220', 'latitude' =>'48.886839', 'longitude' =>'2.296246', 'cover_image' => 'https://www.freebeachclub.com/public/07_camere/oleandri/camere-oleandri-con-terrazza.jpg'],
        ['sommary_title' => 'Appartamento Parigi Saint-Thomas-d Aquin','description' =>'Appartamento ideale per coppie', 'room_number' =>'3','guest_number' =>'2', 'wc_number' =>'1', 'square_meters' =>'100', 'latitude' =>'48.855449', 'longitude' =>'2.321995', 'cover_image' => 'https://www.otrantobiancomare.it/images/appartamenti/app2_1.jpg'],
        ['sommary_title' => 'Appartamento Parigi Gros-Caillou','description' =>'Appartamento con vista sulla tour Eiffel(forse)', 'room_number' =>'6','guest_number' =>'5', 'wc_number' =>'1', 'square_meters' =>'160', 'latitude' =>'48.860419', 'longitude' =>'2.305859', 'cover_image' => 'https://i2.wp.com/villathomas.eu/wp-content/uploads/2018/10/appartamento-di-prestigio.jpg?resize=1434%2C734&ssl=1']

    ]
];
